server:
  port: 8081

spring:
  application:
    name: ORDER-SERVCIE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:// ${DB_HOST:localhost:3306}/${DB_NAME:account}
    username: ${DB_USERNAME:ea}
    password: ${DB_PASSWORD:cs544}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
