apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 2
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: bhbbereket/account-service
          ports:
            - containerPort: 8080
          env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: accountdb
            - name: DB_NAME  # Setting Database name
              value: account
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: acc-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: account
  type: NodePort