apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
data:
  username: cm9vdA==
  password: cm9vdA==

#  cm9vdA==
#  cm9vdA==



#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-secret
#type: kubernetes.io/basic-auth
#stringData:
#  password: test1234


