server:
  port: 9191
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: acc-service
          uri: http://acc-service:8080
          predicates:
              - Path=/api/account/**
          filters:
            - AuthenticationFilter

        - id: ord-service
          uri: http://ord-service:8081
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        - id: pro-service
          uri: http://pro-service:8083
          predicates:
            - Path=/api/product/**
          filters:
            - AuthenticationFilter
jwt:
  secret: bereket
  validity: 20
  authDisabled: true
